#ifndef KORTINLUKUUSI_GLOBAL_H
#define KORTINLUKUUSI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KORTINLUKUUSI_LIBRARY)
#  define KORTINLUKUUSISHARED_EXPORT Q_DECL_EXPORT
#else
#  define KORTINLUKUUSISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // KORTINLUKUUSI_GLOBAL_H
